# Skeleton Dupe by Butter
skeleton-dupe:
  # Turn on the dupe
  enabled: true
  # Chance the item to be duped
  chance: 30

# Donkey Portal Dupe
donkey-dupe:
  # Enables the dupe
  enabled: true
  # Whether the drops should be multiple three times
  triple-drops: false

# Dropper Dupe
dropper-dupe:
  enabled: true
  probability: 100
  cooldown: 1